### ISSUE TITLE
music not playing

### ISSUE THREAD

**Issue by Doriginal** [kumaranvpl/youtubify#1]
hi,

the song not playing, i have put the YouTube api key.

Thank for your help

**Comment by kumaranvpl** [comment]
Version is updated now. Check out now and try again

**Comment by Doriginal** [comment]
not playing with the new version.
in the Chrome console I see a 500 error, I think that's why the song does not play

![capture](https://cloud.githubusercontent.com/assets/1387182/13728166/83257f5c-e90f-11e5-8075-6bae49e55d90.JPG)

**Comment by Doriginal** [comment]
have you an idea?

**Comment by Doriginal** [comment]
Up!

**Comment by kumaranvpl** [comment]
From your attached screenshot this 500 internal server error occurs only for certain calls to /search-audio. Not for all calls. So problem is not with the code

**Comment by Doriginal** [comment]
I have 500 error on all music i will play.
The Search doesn't work (also 500 error, see the screen)
![capture](https://cloud.githubusercontent.com/assets/1387182/13950546/eddcf3b6-f02b-11e5-946f-bbb632a67186.JPG)

**Comment by kumaranvpl** [comment]
In your screenshot, after the first 500 error there is a call which went to search-audio and returned successfully

**Comment by Doriginal** [comment]
No results returned for any researches (spinner turn like the screenshot)
Just "New Releases" display but no sound play on any artists

**Comment by kumaranvpl** [comment]
@Doriginal Will release an update soon

**Comment by Doriginal** [comment]
Thank you

**Comment by kumaranvpl** [comment]
@Doriginal check out the new and updated version 1.8 [here](https://github.com/kumaranvpl/youtubify) or you can download from [releases](https://github.com/kumaranvpl/youtubify/releases/) page.

**Comment by Doriginal** [comment]
Thank you for update.
Not work in local with WAMP server but work in web hosting provider
it's weird
